packages:
  darwin:
    brews:
    - 'git'
    - 'cmake'
    - 'gcc'
    - 'llvm'
    - 'tree'
    - 'tmux'
    - 'neovim'
    - 'sqlite'
    - 'node'
    - 'go'
    - 'python'
    - 'wget'
    - 'bat'
    - 'jq'
    - 'fzf'
    - 'diff-so-fancy'
    - 'chezmoi'
    - 'cargo-binstall'
    - 'anomalyco/tap/opencode'
    casks:
    - 'font-jetbrains-mono-nerd-font'
    - 'google-chrome'
    - 'spotify'
    - 'raycast'
  linuxmint:
    packages:
    - 'openssh-server'
    - 'ripgrep'
    - 'gcc'
    - 'gdb'
    - 'ninja-build'
    - 'gettext'
    - 'cmake'
    - 'curl'
    - 'build-essential'
    - 'git'
    - 'clang'
    - 'nodejs'
    - 'npm'
    - 'tmux'
    - 'jq'

